# PersistentVolumeClaim — disco persistente para mensajes de Kafka
# Si el Pod muere, los mensajes siguen en este disco
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.6.1
          ports:
            - containerPort: 9092
          env:
            # dónde está Zookeeper
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            # LISTENERS — en qué interfaz escucha Kafka dentro del Pod
            # 0.0.0.0 significa "escucha en todas las interfaces" — obligatorio en Kubernetes
            # sin esto Kafka solo escucha en localhost y nadie puede conectarse
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://0.0.0.0:9092"
            # ADVERTISED_LISTENERS — qué dirección anuncia Kafka a los consumers y producers
            # kafka:9092 es el nombre del Service — así otros Pods lo encuentran
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka:9092"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT"
            # necesario para que Kafka sepa qué listener usar entre brokers
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"
            # 1 réplica de cada topic — en producción serían 3
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            # directorio donde Kafka guarda los mensajes — debe coincidir con el mountPath
            - name: KAFKA_LOG_DIRS
              value: "/var/lib/kafka/data"
            # permite crear topics automáticamente cuando un producer publica
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
          volumeMounts:
            - name: kafka-storage
              mountPath: /var/lib/kafka/data
      volumes:
        - name: kafka-storage
          persistentVolumeClaim:
            claimName: kafka-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: default
spec:
  selector:
    app: kafka
  ports:
    - port: 9092
      targetPort: 9092
  type: ClusterIP