apiVersion: v1 #Version de la Api de kubernetes para recursos basicos
kind: ConfigMap #Tipo de configuracion
metadata:
  name: trade-ingestion-config  # nombre único — el Deployment lo referencia exactamente así
  namespace: default           # carpeta lógica donde vive — default es donde van tus apps

    # En Kubernetes localhost no existe — cada Pod tiene su propia IP
  # db-trade-ingestion es el nombre del Service de PostgreSQL dentro del cluster
  # Kubernetes resuelve ese nombre a la IP real del Pod de Postgres automáticamente
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://db-trade-ingestion:5432/trade_ingestion_db"


  # kafka es el nombre del Service de Kafka dentro del cluster
  # Reemplaza el localhost:9092 que tienes en tu application.yml


  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"



 #Puerto de el servidor
  SERVER_PORT: "8082"